---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-hub
  namespace: backend-staging
spec:
  selector:
    matchLabels:
      app: message-hub
  template:
    metadata:
      labels:
        app: message-hub
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: message-hub
        image: ghcr.io/kotollc/koto/messagehub:<TAG>
        imagePullPolicy: Always
        ports:
        - containerPort: 12002
        env:
          - name: KOTO_ADDRESS
            value: ":12002"
          - name: KOTO_EXTERNAL_ADDRESS
            value: https://node1.orbits.at
          - name: KOTO_USER_HUB_ADDRESS
            value: https://central.orbits.at
          - name: KOTO_DB_HOST
            value: db-message-hub-service.backend-staging
          - name: KOTO_DB_SSL_MODE
            value: disable
          - name: KOTO_DB_USER
            value: postgres
          - name: KOTO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-message-hub-password
                key: password
          - name: KOTO_DB_NAME
            value: koto-message-hub-1
          - name: KOTO_S3_ENDPOINT
            value: https://fra1.digitaloceanspaces.com
          - name: KOTO_S3_KEY
            valueFrom:
              secretKeyRef:
                name: message-hub-secrets
                key: s3_key
          - name: KOTO_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: message-hub-secrets
                key: s3_secret
          - name: KOTO_S3_BUCKET
            value: koto-message-hub-1-staging
---
apiVersion: v1
kind: Service
metadata:
  name: message-hub-service
  namespace: backend-staging
spec:
  type: ClusterIP
  selector:
    app: message-hub
  ports:
  - name: http
    port: 12002
