---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-hub
  namespace: backend
spec:
  selector:
    matchLabels:
      app: message-hub
  template:
    metadata:
      labels:
        app: message-hub
    spec:
      terminationGracePeriodSeconds: 5
      hostAliases:
      - ip: "192.168.64.2"
        hostnames:
        - "central.orbits.local"
      containers:
      - name: message-hub
        image: message-hub:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 12002
        env:
          - name: KOTO_ADDRESS
            value: ":12002"
          - name: KOTO_EXTERNAL_ADDRESS
            value: http://node1.orbits.local
          - name: KOTO_USER_HUB_ADDRESS
            value: http://central.orbits.local
          - name: KOTO_DB_HOST
            value: db-message-hub-service.backend
          - name: KOTO_DB_SSL_MODE
            value: disable
          - name: KOTO_DB_USER
            value: postgres
          - name: KOTO_DB_PASSWORD
            value: docker
          - name: KOTO_DB_NAME
            value: koto-message-hub-1
          - name: KOTO_S3_ENDPOINT
            value: https://fra1.digitaloceanspaces.com
          - name: KOTO_S3_KEY
            value: minioadmin
          - name: KOTO_S3_SECRET
            value: minioadmin
          - name: KOTO_S3_BUCKET
            value: koto-message-hub-1
---
apiVersion: v1
kind: Service
metadata:
  name: message-hub-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: message-hub
  ports:
  - name: http
    port: 12002
