---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: backend
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: node
        image: k0t0/node:v1.0
        ports:
        - containerPort: 12002
        env:
          - name: KOTO_ADDRESS
            value: ":12002"
          - name: KOTO_EXTERNAL_ADDRESS
            value: http://node-service.backend:12002/
          - name: KOTO_CENTRAL_ADDRESS
            value: http://central-service.backend:12001/
          - name: KOTO_DB_HOST
            value: db-node-service.backend
          - name: KOTO_DB_SSL_MODE
            value: disable
          - name: KOTO_DB_USER
            value: postgres
          - name: KOTO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-node-password
                key: password
          - name: KOTO_DB_NAME
            value: koto-node-1
          - name: KOTO_S3_ENDPOINT
            value: "s3-service:9000"
          - name: KOTO_S3_KEY
            valueFrom:
              secretKeyRef:
                name: node-secrets
                key: s3_key 
          - name: KOTO_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: node-secrets
                key: s3_secret
          - name: KOTO_S3_BUCKET
            value: koto-node-1
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: node
  ports:
  - name: http
    port: 12002
