---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-staging
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: frontend
        image: peacenikapp/frontend:<TAG>
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: KOTO_USER_HUB_ADDRESS
            value: https://central.orbits.at
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-staging
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 5000
