version: "3.7"

services:
  node:
    image: k0t0/node:latest
    volumes:
      - ${VOLUME_NODE}:/data
    ports:
      - 12001:12001
    environment:
      KOTO_LISTEN_ADDRESS: :12001
      KOTO_EXTERNAL_ADDRESS: ${KOTO_EXTERNAL_ADDRESS}
      KOTO_CENTRAL_ADDRESS: ${KOTO_CENTRAL_ADDRESS}
      KOTO_DB_HOST: db
      KOTO_DB_SSL_MODE: disable
      KOTO_DB_USER: ${KOTO_DB_USER}
      KOTO_DB_PASSWORD: ${KOTO_DB_PASSWORD}
      KOTO_DB_NAME: koto-node
      KOTO_S3_ENDPOINT: ${KOTO_S3_ENDPOINT}
      KOTO_S3_REGION: ${KOTO_S3_REGION}
      KOTO_S3_KEY: ${KOTO_S3_KEY}
      KOTO_S3_SECRET: ${KOTO_S3_SECRET}
      KOTO_S3_BUCKET: ${KOTO_S3_BUCKET}
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:12.3
    volumes:
      - ${VOLUME_DB}:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: koto-node
      POSTGRES_USER: ${KOTO_DB_USER}
      POSTGRES_PASSWORD: ${KOTO_DB_PASSWORD}
