---
apiVersion: v1
kind: Namespace
metadata:
  name: sponsored-hubs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-<NAME>
  namespace: sponsored-hubs
spec:
  selector:
    matchLabels:
      app: message-hub
  template:
    metadata:
      labels:
        app: message-hub
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: message-hub
        image: k0t0/node:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 12002
        env:
          - name: KOTO_ADDRESS
            value: ":12002"
          - name: KOTO_EXTERNAL_ADDRESS
            value: https://<NAME>.orbits.at
          - name: KOTO_USER_HUB_ADDRESS
            value: https://central.orbits.at
          - name: KOTO_DB_HOST
            value: db-message-hub-service.backend-staging
          - name: KOTO_DB_SSL_MODE
            value: disable
          - name: KOTO_DB_USER
            value: postgres
          - name: KOTO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-message-hub-password
                key: password
          - name: KOTO_DB_NAME
            value: koto-message-hub-<NAME>
          - name: KOTO_S3_ENDPOINT
            value: https://fra1.digitaloceanspaces.com
          - name: KOTO_S3_KEY
            valueFrom:
              secretKeyRef:
                name: message-hub-secrets
                key: s3_key
          - name: KOTO_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: message-hub-secrets
                key: s3_secret
          - name: KOTO_S3_BUCKET
            value: koto-message-hub-<NAME>-staging
---
apiVersion: v1
kind: Service
metadata:
  name: hub-service-<NAME>
  namespace: sponsored-hubs
spec:
  type: ClusterIP
  selector:
    app: message-hub
  ports:
  - name: http
    port: 12002
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: koto-<NAME>
  namespace: sponsored-hubs
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "do-issuer"
    # acme.cert-manager.io/http01-edit-in-place: "true"
    # cert-manager.io/issue-temporary-certificate: "true"
spec:
  tls:
  - hosts:
    - "*.orbits.at"
    secretName: koto-tls-backend
  rules:
  - host: <NAME>.orbits.at
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hub-service-<NAME>
            port:
              number: 12002
