---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-hub-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: db-user-hub-service
  labels:
    app: db-user-hub-service
spec:
  ports:
    - port: 5432
  selector:
    app: db-user-hub-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user-hub-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-user-hub-service
  template:
    metadata:
      labels:
        app: db-user-hub-service
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          env:
          - name: POSTGRES_DB
            value: koto-user-hub
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-hub-password
                key: password
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: user-hub-db-data
            mountPath: /var/lib/postgresql
      volumes:
      - name: user-hub-db-data
        persistentVolumeClaim:
          claimName: user-hub-db-pvc
