---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: frontend
        image: k0t0/frontend:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: KOTO_CENTRAL_HOST
            value: central-service.backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 5000
