---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central
spec:
  selector:
    matchLabels:
      app: central
  template:
    metadata:
      labels:
        app: central
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
        - name: central-key
          secret:
            secretName: central-key
      containers:
      - name: central
        image: k0t0/central:v1.11
        imagePullPolicy: Always
        ports:
        - containerPort: 12001
        volumeMounts:
          - name: central-key
            mountPath: "/tmp"
        env:
          - name: KOTO_ADDRESS
            value: ":12001"
          - name: KOTO_PRIVATE_KEY
            value: /tmp/key
          - name: KOTO_ADMINS
            value: matt
          - name: KOTO_DB_HOST
            value: db-central-service
          - name: KOTO_DB_SSL_MODE
            value: disable
          - name: KOTO_FRONTEND_ADDRESS
            value: http://koto.at
          - name: KOTO_DB_USER
            value: postgres
          - name: KOTO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-central-password
                key: password
          - name: KOTO_DB_NAME
            value: koto-central
          - name: KOTO_S3_ENDPOINT
            value: https://storage.googleapis.com
          - name: KOTO_S3_KEY
            valueFrom:
              secretKeyRef:
                name: central-s3
                key: s3_key
          - name: KOTO_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: central-s3
                key: s3_secret
          - name: KOTO_S3_BUCKET
            value: koto-central
          - name: KOTO_SMTP_HOST
            value: smtp.sendgrid.net
          - name: KOTO_SMTP_PORT
            value: "587"
          - name: KOTO_SMTP_USER
            valueFrom:
              secretKeyRef:
                name: central-smtp
                key: smtp_user
          - name: KOTO_SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: central-smtp
                key: smtp_password
          - name: KOTO_SMTP_FROM
            value: admin@koto.at
          - name: KOTO_TEST_MODE
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: central-service
spec:
  type: NodePort
  selector:
    app: central
  ports:
  - name: http
    port: 12001
