on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'     
        required: true
jobs:
  announce:
    name: announce-things
    runs-on: ubuntu-latest
    steps:    
    - name: announcement
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
        severity: info
        color: '#ff00aa'
        avatarUrl: https://user-images.githubusercontent.com/118036/104819208-50108f80-582c-11eb-830d-ced2ea30ce0f.png
        description: Peacenik announcement
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        details: ${{ github.event.inputs.message }}