on: 
  workflow_dispatch:
jobs:
  build-and-publish:
    name: Build and Publish images
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code
        with:
          ref: '${{ github.event.inputs.branch}}'

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Publish Frontend
        with:
          image: koto/frontend
          tags: ${{ github.run_number }}, latest
          registry: ghcr.io
          githubOrg: kotollc
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }} 
          directory: ./frontend

          dockerfile: ./frontend/Dockerfile.production

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Publish Userhub
        with:
          image: koto/userhub
          tags: ${{ github.run_number }}, latest
          registry: ghcr.io
          githubOrg: kotollc
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
          directory: ./backend
          dockerfile: ./backend/userhub/Dockerfile

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Publish Messagehub
        with:
          image: koto/messagehub
          tags: ${{ github.run_number }}, latest
          registry: ghcr.io
          githubOrg: kotollc
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }} 
          directory: ./backend
          dockerfile: ./backend/messagehub/Dockerfile
      - name: Slack notify
        uses: edge/simple-slack-notify@master
        with:
          channel: '#engineering'
          text: 'Image number ${{ github.run_number }} published to Github registry'
          color: 'good'
