on:
  push:
    tags:
      - '*staging'
jobs:
  build:
    name: Build and Publish images
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - uses: whoan/docker-build-with-cache-action@v5
        name: Build & push Frontend Docker image
        with:
          image_name: k0t0/frontend
          image_tag: ${{ steps.get_version.outputs.VERSION }},latest
          context: ./frontend
          dockerfile: Dockerfile.production
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: whoan/docker-build-with-cache-action@v5
        name: Build & push Backend User Hub Docker image
        with:
          image_name: k0t0/central
          image_tag: ${{ steps.get_version.outputs.VERSION }},latest
          context: ./backend
          dockerfile: userhub/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: whoan/docker-build-with-cache-action@v5
        name: Build & push Backend Message Hub Docker image
        with:
          image_name: k0t0/node
          image_tag: ${{ steps.get_version.outputs.VERSION }},latest
          context: ./backend
          dockerfile: messagehub/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build

    env:
      DO_CLUSTER_ID: "b68876cd-8a1d-4073-bb00-0ac36beacc0c"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install Doctl
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ env.DO_CLUSTER_ID }}

      - name: Update deployment file (staging)
        run: |
          sed -i 's|<TAG>|'${{ needs.build.outputs.version }}'|' $GITHUB_WORKSPACE/.k8s/backend-staging/user-hub.yaml
          sed -i 's|<TAG>|'${{ needs.build.outputs.version }}'|' $GITHUB_WORKSPACE/.k8s/frontend-staging/frontend.yaml
          sed -i 's|<TAG>|'${{ needs.build.outputs.version }}'|' $GITHUB_WORKSPACE/.k8s/backend-staging/message-hub.yaml

      - name: Deploy Frontend and User-hub to DigitalOcean Kubernetes (staging)
        run: |
          kubectl apply -f $GITHUB_WORKSPACE/.k8s/backend-staging/user-hub.yaml --force
          kubectl apply -f $GITHUB_WORKSPACE/.k8s/frontend-staging/frontend.yaml --force
          kubectl apply -f $GITHUB_WORKSPACE/.k8s/backend-staging/message-hub.yaml --force

 