apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: koto-ingress1
  namespace: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - "peacenik.app"
    secretName: koto-tls-backend
  rules:
  - host: peacenik.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port: 
              number: 80